# Based on
#
#   - https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases
#   - https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml
#   - https://alican.codes/rust-github-actions
on:
  push:
    tags:
      - 'v[0-9]+.*'

name: Release binary

jobs:
  release:
    name: Perform release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          run: cargo build --all --release && strip target/release/beeminder && mv target/release/beeminder target/release/beeminder_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/beeminder_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
